version: '3.7'

services:
  postgres:
    image: postgres:13.0
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:5000

  redis:
    image: redis:6.0.3
    expose:
      - 6379

  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    expose:
      - 5001
    volumes:
      - ./data:/data/

  web-aserve:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    entrypoint:
      - /app/web
      - aserve
    expose:
      - 5003
    volumes:
      - ./data:/data/

  auth:
    build:
      context: ./
      dockerfile: ./docker/auth.dockerfile
    expose:
      - 5002

networks:
  default:
    driver: bridge
