version: '3.7'

services:
  db-postgres:
    image: postgres
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  lb-nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:5000
    network_mode: host

  redis:
    image: redis:6.0.3
    ports:
      - "6379:6379"
    network_mode: host

  web:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    ports:
      - 5001:5001
    network_mode: host

  auth:
    build:
      context: ./
      dockerfile: ./docker/auth.dockerfile
    ports:
      - 5002:5002
    network_mode: host
