version: '3.7'

services:
  mysql:
    image: mysql:8.0.23
    environment:
      - MYSQL_DATABASE=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ../mysql_data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306

  # gui:
  #   build:
  #     context: ../
  #     dockerfile: ./delivery-gui/docker/Dockerfile
  #   ports:
  #     - 6000:6000
  #   volumes:
  #     - ../data:/data/

networks:
  default:
    driver: bridge
